language: go

go: 
  - 1.15.x

env:
  - GO111MODULE=on

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo

script:
  ginkgo -r --randomizeAllSpecs --randomizeSuites --cover --trace --progress